### ISSUE TITLE
Folded affects the dock

### ISSUE THREAD

**Issue by andrwmai** [Thomz07/Folded#3]
**Describe the bug**
When enabled, Folded moves the last icon on the right of the dock to be above the the first one on the right and cover it (as shown in the screenshot). Safari covers Spotify so you can’t see it. Disabling Folded resolves the issue. I don’t know how Folded can affect the dock, but welp... Also it only affects the dock if it has more than 4 icons.

**To Reproduce**
Just set the number of icons in the dock to something more than 4 and it’ll affect it right away.

**Screenshots**

**iOS Version:**
iOS 13.3

**iPhone:**
iPhone Xs Max
![2651340C-4613-478D-BB52-EEBDEC0DFC3E](https://user-images.githubusercontent.com/48293860/78459415-fa2a8b00-76e2-11ea-8b19-c93bffb95645.png)

**Comment by ren7995** [comment]
Good news! Folded version 1.0.2 will fix this, and hopefully be available on Packix shortly!

Good day to you.

**Comment by andrwmai** [comment]
Thank you guys! Love the work and the effort put into the tweak! :)

Good day to you too!
