### ISSUE TITLE
Icon view on springboard glitches after app update

### ISSUE THREAD

**Issue by hmenzagh** [Thomz07/Folded#4]
**Describe the bug**
The icon view on springboard glitches after app update

**To Reproduce**
Use preset "modern look", and update any app in a folder

**Expected behavior**
The icon view on the springboard should stay 3*3

**Screenshots**
![IMG_0DB62BAF733E-1](https://user-images.githubusercontent.com/21102398/78912433-e20e8f00-7a87-11ea-9c82-46e4fa51aa0b.jpeg)

**iOS Version:**
- 13.3.1

**iPhone:**
 - iPhone X

**Extra info:**
All returns back to normal after a respring

**Comment by ren7995** [comment]
There is a note about it in settings. We are working on a fix. 

Good day to you.

**Comment by ren7995** [comment]
Actually, my bad, there isn’t.

**Comment by hmenzagh** [comment]
Np thanks for the reply & the good work !

**Comment by Jefferoni-Maloni** [comment]
Model: iPhone 8 Plus
iOS Version: 13.3.1

Having a similar issue. I used the 3x5 preset, changed it to 4x5, and set custom folder grid to 3x3. Adding many apps to a folder causes same issue shown above. 

Before:
![Before](https://user-images.githubusercontent.com/26368662/79172318-fc16dd00-7db9-11ea-813b-5a3d3fbeda42.png)

After:
![After](https://user-images.githubusercontent.com/26368662/79172326-00db9100-7dba-11ea-9093-1f20cd848f09.png)

And another issue that may need a different issue. When dragging around a folder with conditions above, it also doesn't respect the custom folder grid:

![Other](https://user-images.githubusercontent.com/26368662/79172357-1bae0580-7dba-11ea-927b-6cad908636e8.png)

**Comment by ren7995** [comment]
Ok, thank you for reporting this, I actually didn’t know dragging it around would do that. 

Good day!

**Comment by DiscoBoyAlvin** [comment]
iPhone Xr 13.3

• After enabling manually or automatically Dark and light mode, the icon grid doesn’t stay as 3x3, but rather the folder opened layout. 

This also happens when moving icons in and out of folders.

Also occurs when you open an app and modify something in app i.e. Snowboard, altstore etc

• Homeplus Beta causes the grid layout inside to be a weird spaced out 3x3. 
Pleeeease make it compatible or something :)

**Comment by ren7995** [comment]
Fixed in 1.2.0 update! :)
