### ISSUE TITLE
Grid Icon Problems

### ISSUE THREAD

**Issue by ghost** [Thomz07/Folded#5]
iPhone Xr 13.3

• After enabling manually or automatically Dark and light mode, the icon grid doesn’t stay as 3x3, but rather the folder opened layout. 

This also happens when moving icons in and out of folders.

Also occurs when you open an app and modify something in app i.e. Snowboard, altstore etc

• Homeplus Beta causes the grid layout inside to be a weird spaced out 3x3. 
Pleeeease make it compatible or something :)

_Originally posted by @DiscoBoyAlvin in https://github.com/Thomz07/Folded/issues/4#issuecomment-617682483_

**Comment by chendovdtoorn** [comment]
I have the same issue with the grid layout in combination with the HomePlus Beta tweak

HomePlus Beta disabled (as it should be):
![A3F30F11-C9A1-4303-A930-F6798BCA31E4](https://user-images.githubusercontent.com/56150402/83984799-22c73f00-a937-11ea-8714-ab211e675ef4.png)

HomePlus Beta enabled:
![E5CCD612-C4A1-432A-B8CC-D6C26BA122E7](https://user-images.githubusercontent.com/56150402/83984837-42f6fe00-a937-11ea-817c-1c94b9b3aa85.png)

**Comment by ghost** [comment]
Layout is fixed with ‘Homeplus Pro’
