### ISSUE TITLE
Folded app icon bug

### ISSUE THREAD

**Issue by dongmin-dev** [Thomz07/Folded#7]
**Describe the bug**
When I install folded tweak, the app's icon I move from the folder is still there. I will add a video about it
I tried reset preferences too but did not work.

**To Reproduce**
1. Install Folded
2. Press any app from the folder
3. Take it out from the folder

**Expected behavior**
The app icon is still in the folder.

**Screenshots**
https://share.icloud.com/photos/01wLpX-ruXZ27XMu-Zci_8QHw
Demonstrating the bug

**iOS Version:**
- iOS 13.5

**iPhone:**
 - Device: iPhone XR

**Comment by 301nav** [comment]
By any chance do you have the tweak IconState installed? That would be the reason why that happens then. You would need to respring your device to fix the look of the folder icon

**Comment by dongmin-dev** [comment]
> By any chance do you have the tweak IconState installed? That would be the reason why that happens then. You would need to respring your device to fix the look of the folder icon

Unfortunately, the tweak has never been installed. I know that respring will solve the problem temporarily, but is there no proper solution?

**Comment by 301nav** [comment]
> > By any chance do you have the tweak IconState installed? That would be the reason why that happens then. You would need to respring your device to fix the look of the folder icon
> 
> Unfortunately, the tweak has never been installed. I know that respring will solve the problem temporarily, but is there no proper solution?

Honestly I’m not too sure. Maybe you have another tweak that has a similar function to IconState built into it? That’s all I can really think of to be honest. Sorry man

EDIT: I looked at the tweak description in Installer 5 and in the update notes for v 1.2.0 it mentions “Icons of folders now update only after resprings to prevent ugly looking folders”. I believe this may be the reason you are having this issue

**Comment by dongmin-dev** [comment]
So you're saying that my problem will be solved if I delete installer5 and rejailbreak? Thank you very much. 🙏🙏
